#JUST A RANDOM FILE
print("Hello, Everyone!")
print()
print()
print("My First Project(s) : Dice Rolling v1.0 and v2.0")
print("Basic Version from GeeksforGeeks.")
print()
print()
print("My Second Project: Number Guessing Game")
print("Basic Version from Coursera.")
print()
print()
print("My Third Project: Word Guessing Game")
print("Basic version from GeeksforGeeks.")
print()
print()
print("My Fourth Project: Basic Calculator v1 and v2")
print("Basic version from GreatLearning.")
print("Modified version of Calculator(CodSoft Internship).")
print()
print()
print("My Fifth Project: Cantact Book.")
print("One of the tasks from CodSoft Internship.")
print()
print()
